# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d02adda500ac43807595c53b12f2e6affdb4cf7411fc692743197fde9dcdff20a6771b91395ef562a0643934d3fda0079baf12d91210d40732bd5019b29734d8

test:
  secret_key_base: 203582a7986dd8a2b193dec0bd1222e0d01c4f206558506254e7a42c134cea97ece368fb52125492664f5e885d34d120387af29d0cc7c3c8b355d6d4fd6ebd73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
